version: '3.7'

services:
  minio.docker:
    image: minio/minio:RELEASE.2020-01-25T02-50-51Z
    volumes:
      - ./data:/data
    ports:
      - "19002:9000"
    environment:
      MINIO_ACCESS_KEY: MinioAccessKey
      MINIO_SECRET_KEY: MinioSecretKey
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:19002/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3